---
- name: Configurar y provisionar una máquina con Docker
  hosts: all
  become: yes

  tasks:
    - name: Actualizar los repositorios de paquetes y la caché
      apt:
        update_cache: yes

    - name: Instalar paquetes necesarios para Docker
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
        state: present

    - name: Añadir la clave GPG oficial de Docker
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Añadir el repositorio de Docker a las fuentes de APT
      apt_repository:
        repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
        state: present

    - name: Actualizar los repositorios de paquetes con el repositorio de Docker añadido
      apt:
        update_cache: yes

    - name: Instalar Docker
      apt:
        name: docker-ce
        state: present

    - name: Habilitar el servicio de Docker
      systemd:
        name: docker
        enabled: yes
        state: started
