Vagrant.configure("2") do |config|
    # Especifica la box que deseas utilizar
    config.vm.box = "ubuntu/bionic64"  # Esto usa Ubuntu 18.04 (Bionic Beaver)
  
    # Configurar el provisionador de Ansible
    config.vm.provision "ansible_local" do |ansible|
      ansible.playbook = "playbook.yml"  # Ruta al playbook de Ansible en formato YAML
    end
  end
  